version: '3.4'

services:
  loginservicedb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    volumes:
      - loginservice-sql-server-data:/var/opt/mssql/data
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Pa55word!"
       MSSQL_PID: "Express"
    ports:
      - "1434:1433"

  loginserviceapi:
    image: loginserviceapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__ClassroomServiceDB: "Server=loginservicedb,1433;Database=LoginServiceDB;User ID=SA;Password=Pa55word!;MultipleActiveResultSets=true;"
    volumes:
      - $APPDATA\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - $USERPROFILE\.aspnet\https\:/root/.aspnet/https/
    ports:
      - 5001:443
    depends_on:
      - loginservicedb
    
volumes:
  loginservice-sql-server-data: {}
