version: '3.4'

services:
  oes.web.bff:
    image: oes.web.bff
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5002"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - $APPDATA\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - $USERPROFILE\.aspnet\https\:/root/.aspnet/https/
    ports:
      - 5000:80
      - 5002:443
